const axios = require('axios');
const fs = require('fs');
const path = require('path');

/**
 * NATIONAL DISTRICT HARVESTER
 * Fetches all 700+ administrative districts directly from Boundary Registries
 */
const harvestDistricts = async () => {
    console.log("[SYSTEM] Initializing National District Harvester...");
    
    // Using a high-precision boundary query
    const query = `
        [out:json][timeout:120];
        area["name"="India"]["admin_level"="2"]->.country;
        (
          rel["admin_level"="5"](area.country);
        );
        out tags;
    `;

    try {
        const response = await axios.post('https://overpass-api.de/api/interpreter', `data=${encodeURIComponent(query)}`);
        const elements = response.data.elements || [];
        
        console.log(`[SYSTEM] Discovered ${elements.length} primary districts.`);

        const districtMap = {};
        
        elements.forEach(el => {
            const state = el.tags["is_in:state"] || el.tags.state_name || "Unknown State";
            const district = el.tags.name;
            
            if (!districtMap[state]) districtMap[state] = new Set();
            districtMap[state].add(district);
        });

        const finalData = Object.keys(districtMap).map(state => ({
            state: state,
            districts: Array.from(districtMap[state]).sort()
        })).sort((a, b) => a.state.localeCompare(b.state));

        const outputPath = path.join(__dirname, '..', 'data', 'indiaDistricts.js');
        const fileContent = `// BHARAT-REGISTRY: AUTOGENERATED NATIONAL DISTRICT LIST
// Generated on: ${new Date().toISOString()}
module.exports = ${JSON.stringify(finalData, null, 4)};`;

        fs.writeFileSync(outputPath, fileContent);
        console.log(`[SUCCESS] National Registry updated at: ${outputPath}`);
        console.log(`[SUMMARY] Total States/UTs: ${finalData.length}`);
        console.log(`[SUMMARY] Total Districts Harvested: ${elements.length}`);

    } catch (err) {
        console.error("[ERROR] Harvesting Failed:", err.message);
    }
};

harvestDistricts();
